version: '3'

services:
  grafana:
    image: grafana/grafana-oss:9.4.3
    ports:
      - 3000:3000
    restart: unless-stopped 
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
    volumes:
      - grafana-data:/var/lib/grafana
      - ./db:/db/
      # - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
  
  scraper:
    build:
      # context: .
      context: https://github.com/gloriousDan/danfoss_grafana.git#main
    env_file:
      - .env
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./db:/app/db

volumes:
  grafana-data:
    driver: local
