{
 "title": "Photovoltaik Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Alle Werte",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "Select * from danfoss",
     "rawQueryText": "Select * from danfoss",
     "timeColumns": [
      "time",
      "ts",
      "TIMESTAMP"
     ]
    }
   ]
  },
  {
   "title": "Energie pro Tag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "queryText": "SELECT TIMESTAMP, E_DAY FROM \"danfoss\"",
     "rawQueryText": "SELECT TIMESTAMP, E_DAY FROM \"danfoss\"",
     "timeColumns": [
      "time",
      "ts",
      "TIMESTAMP"
     ]
    }
   ]
  },
  {
   "title": "Ausgangsleistung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "queryText": "SELECT TIMESTAMP, P_AC FROM \"danfoss\"",
     "rawQueryText": "SELECT TIMESTAMP, P_AC FROM \"danfoss\"",
     "timeColumns": [
      "time",
      "ts",
      "TIMESTAMP"
     ]
    }
   ]
  },
  {
   "title": "Energie pro Tag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "queryText": "SELECT TIMESTAMP, E_DAY FROM \"danfoss\"",
     "rawQueryText": "SELECT TIMESTAMP, E_DAY FROM \"danfoss\"",
     "timeColumns": [
      "time",
      "ts",
      "TIMESTAMP"
     ]
    }
   ]
  }
 ]
}